### ISSUE TITLE
检测不了物体

### ISSUE THREAD

**Issue by ztyf-pytorch** [PeizeSun/SparseR-CNN#101]
作者大大您好，我想学习您的论文，但是在跑deom的时候，出现了以下提示：[01/17 19:30:01 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
  stem.fc.{bias, weight}
然后我跑demo在我指定上的图片实际上有物体，但是检测不出来，于是我就调整confidence-threshold，发现0.2以上都检测不了物体，在0.2以下检测有物体，但是检测结果是混乱的。我用的是您的权重，每个都试过了一次。请问能帮我解答吗？谢谢。

**Comment by PeizeSun** [comment]
Hi~
You should use the trained models, instead of ImageNet pre-trained models.
