### ISSUE TITLE
About performance of Sparse R-CNN

### ISSUE THREAD

**Issue by ty1234567454** [PeizeSun/SparseR-CNN#105]
Hi, I'm a reader of your paper -  Sparse R-CNN: End-to-End Object Detection with Learnable Proposals. I have a question about the performance.

In your first version on arxiv, the AP on R50-300-queries is 44.5, whereas this is changed to 45.0 in your second version. I wonder why. Is there some improvement on the later version of Sparse R-CNN? I have read your code but have not found anything special.
My email: ty1234567454@gmail.com

![image](https://user-images.githubusercontent.com/102733129/161203752-3b6e60b9-cfea-4dfe-a3c9-5a44b0d57629.png)
![image](https://user-images.githubusercontent.com/102733129/161203769-7749627b-aeaf-4f79-bf62-288144a54441.png)

**Comment by alt-Pranav** [comment]
Hi, could you share what information you received about your above issue?
Furthermore, did you ever see any difference in inference on video vs image (where image is a frame of the video)?
