### ISSUE TITLE
STRIDE_IN_1X1=True for torchvision models?

### ISSUE THREAD

**Issue by bobokeley** [PeizeSun/SparseR-CNN#12]
Thanks for this very intriguing work!

I found that you used torchvision pretrained models instead of MSRA pretrained ones while setting STRIDE_IN_1X1=True, which is somehow inconsistent with torchvision resnet. I reproduced a model using MSRA R-50 backbone w/ dropout=0.1, and it turned out that it is 0.7% AP lower than the reported one w/ dropout, probably indicating that differently pretrained backbones kinda matters. Maybe there can be some further improvement if this configuration inconsistency is fixed.

**Comment by PeizeSun** [comment]
Hi~
All settings of STRIDE_IN_1X1 in our code is False, not True.
In genearal, torchvision pretrained models and MSRA pretrained ones won't make a difference. If you use MSRA pretrained models, you should set :  
INPUT.FORMAT: "BGR"
MODEL.RESNETS. STRIDE_IN_1X1: True
MODEL.PIXEL_MEAN: [103.530, 116.280, 123.675]
MODEL.PIXEL_STD to [1, 1, 1]

**Comment by bobokeley** [comment]
Thanks for your reply, I just probably found the real inconsistency between my configuration and yours which causes the drop (gradient clip is not enabled in my case). Closing the issue.
