### ISSUE TITLE
result not as good as expected?

### ISSUE THREAD

**Issue by jinfagang** [PeizeSun/SparseR-CNN#16]
![image](https://user-images.githubusercontent.com/21303438/100689563-aaaa7500-33bf-11eb-8602-b28a46f5171d.png)

thresh set as default....

**Comment by jinfagang** [comment]
If set to 0.1
![image](https://user-images.githubusercontent.com/21303438/100689660-d4639c00-33bf-11eb-8f02-02ef38626a7e.png)

**Comment by zzzzzz0407** [comment]
@jinfagang We are sorry that there is a bug in our demo, specifically, the model trained in our default cfg is with "RGB" format, however, we find that the format of input image in demo.py is "BGR", we will fix this bug latter.
You can try it here https://github.com/PeizeSun/SparseR-CNN/blob/main/demo/demo.py#L88.
Look forward to your reply.

**Comment by jinfagang** [comment]
I converted to RGB:

![image](https://user-images.githubusercontent.com/21303438/100692732-6a9ac080-33c6-11eb-962c-c6a69434c597.png)

**Comment by zzzzzz0407** [comment]
@jinfagang can u share the original picture? We will test it latter.

**Comment by jinfagang** [comment]
coco image with name `000000578489.jpg`. To be honestly, this is a randome image.

**Comment by JunnYu** [comment]
@jinfagang @zzzzzz0407 
This is my test output.
```python
PS E:\2020code\november\junnyu_github\SparseR-CNN-main> python demo/demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.300pro.3x.yaml --input 000000578489.jpg --confidence-threshold 0.4 --opts MODEL.WEIGHTS ./r50_300pro_3x_model.pth
                              [12/03 19:29:56 detectron2]: Arguments: Namespace(confidence_threshold=0.4, config_file='projects/SparseRCNN/configs/sparsercnn.res50.300pro.3x.yaml', input=['000000578489.jpg'], opts=['MODEL.WEIGHTS', './r50_300pro_3x_model.pth'], output=None, video_input=None, webcam=False)      
[12/03 19:29:59 fvcore.common.checkpoint]: Loading checkpoint from ./r50_300pro_3x_model.pth
[12/03 19:30:02 detectron2]: 000000578489.jpg: detected 10 instances in 1.72s
```
![8ASU P_{@_ EHL2IENRRKW0](https://user-images.githubusercontent.com/50394665/101012569-ff0b4b80-359d-11eb-84da-c733b8c36603.png)

**Comment by PeizeSun** [comment]
@jinfagang @zzzzzz0407 @JunnYu Hi~

The right way to convert to rgb format is:
First, change **img = read_image(path, format="BGR")** in original demo.py to **img = read_image(path, format="RGB")**
https://github.com/PeizeSun/SparseR-CNN/blob/main/demo/demo.py#L90
Then, comment **image = image[:, :, ::-1]** in original predictor.py
https://github.com/PeizeSun/SparseR-CNN/blob/main/demo/predictor.py#L51
