### ISSUE TITLE
Unbalance of number of objects in images

### ISSUE THREAD

**Issue by hzh8311** [PeizeSun/SparseR-CNN#17]
what should I do if I want train for dataset which the number of objects in a wide range, say 1~1000. Setting proposals number to a huge number seem not a good choice.

**Comment by PeizeSun** [comment]
Hi, 
Setting proposals number to a huge number **in all stages** is definitely a bad choice. How about setting a huge number in first stage, and then gradually reducing the number, e.g., only selecting the proposal with high score?

**Comment by ZJU-lishuang** [comment]
if a image only has one or two objects in the train datatset,can I set NUM_PROPOSALS to 10?

**Comment by PeizeSun** [comment]
I guess it is hard to say yes or no unless the experiment is carried out.
