### ISSUE TITLE
What is the "instance interaction"?

### ISSUE THREAD

**Issue by tangjiuqi097** [PeizeSun/SparseR-CNN#2]
Hi, I do not know what is the "instance interaction" in Table 4. 
It is just explained in a few words and could you tell me what it is with more detail?

![image](https://user-images.githubusercontent.com/22868536/100201395-f7fb9200-2f3a-11eb-90d5-9b681597dc67.png)
![image](https://user-images.githubusercontent.com/22868536/100201489-13669d00-2f3b-11eb-80a2-5d45d1b1e2de.png)

**Comment by PeizeSun** [comment]
Hi~
The instance interaction is shown in Figure 4 of paper:
![image](https://user-images.githubusercontent.com/40374966/100202806-c4216c00-2f3c-11eb-87cf-f494258a3070.png)

The code of instance interaction is at:
https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseR-CNN/sparsercnn/head.py#L194

**Comment by tangjiuqi097** [comment]
Thanks for your answer. I had been confused by the dynamic head in table 2 and the instance interaction in table 4.
