### ISSUE TITLE
nan in boxes when training

### ISSUE THREAD

**Issue by Kongsea** [PeizeSun/SparseR-CNN#21]
I have setup the environment according to the repository instructions and train a model using my own custom dataset.
The training always encounter the following error:

```
File "SparseR-CNN/projects/SparseRCNN/sparsercnn/util/box_ops.py", line 51, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all(), boxes1
AssertionError: tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0', requires_grad=True
)
```

As you can see, I print out the `boxes` when encountering the error and it has some nan values.

I have tried to decrease learning rate from 0.01 to 0.005 and even 0.0025, but the error is still there.

So could you help me to fix it? Thank you.

**Comment by zzzzzz0407** [comment]
@Kongsea The default learning rate in our paper is 0.000025, your learning rate may be too large. 
If your batchsize is less then 16, the learning rate should be even much smaller.

**Comment by Kongsea** [comment]
The error has been fixed after decreasing lr. Thank you.
