### ISSUE TITLE
how to get rois's grad in roi_align

### ISSUE THREAD

**Issue by fengxiuyaun** [PeizeSun/SparseR-CNN#27]
@PeizeSun 
hi, thanks your share code. I dont understand how to get rois's grad in roi_align,

**Comment by PeizeSun** [comment]
Hi~
Actually, gradient of proposal box is not passed by RoI_align. The mechanics is: predicted_box = proposal_box + offset, when gradient is back-propagate to predicted_box, then gradient is to both offset and proposal_box.

**Comment by fengxiuyaun** [comment]
thank you very much.  thks, thks.

**Comment by cyy21** [comment]
@fengxiuyaun there is an aux loss for all 6 head, you can understand that when backward, all 6 head is Parallel

**Comment by GengDavid** [comment]
@PeizeSun Hi, I'm also curious about the optimization of the learnable proposal bbox, and find that in the iterative refinement, the generated `bboxes` is detached [here](https://github.com/PeizeSun/SparseR-CNN/blob/ca36868709063351c503e260d21f37c803223870/projects/SparseRCNN/sparsercnn/head.py#L109). Is there any specific reason to detach it from iterative refinement?

**Comment by PeizeSun** [comment]
> @PeizeSun Hi, I'm also curious about the optimization of the learnable proposal bbox, and find that in the iterative refinement, the generated `bboxes` is detached [here](https://github.com/PeizeSun/SparseR-CNN/blob/ca36868709063351c503e260d21f37c803223870/projects/SparseRCNN/sparsercnn/head.py#L109). Is there any specific reason to detach it from iterative refinement?

We found that detaching it could get the better result than not detaching.
