### ISSUE TITLE
assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

### ISSUE THREAD

**Issue by lg12170226** [PeizeSun/SparseR-CNN#29]
when i train my own data,report err assert (boxes1[:, 2:] >= boxes1[:, :2]).all() -> cost_giou = -generalized_box_iou(out_bbox, tgt_bbox).but the boxes1 is out_bbox.the same data  were  trained in detectron2 is ok.thanks

**Comment by Kongsea** [comment]
Decreasing your lr can solve it.

**Comment by lg12170226** [comment]
thanks @Kongsea
