### ISSUE TITLE
训练过程中boxes坐标前向传播结果为nan

### ISSUE THREAD

**Issue by sunnnnnnnnnnnnnnn** [PeizeSun/SparseR-CNN#30]
我在训练Sparse-rcnn的过程中，在project/Sparse-rcnn/sparsercnn/box_ops.py中对应的地方抛出了boxes的坐标值不合法的错误。请问可能是什么原因导致的呢？    我打印了boxes的坐标值，发现其中是4个nan，网络结构和数据集都没有修改过。训练使用的是两张2080ti，batch size是8，学习率是0.0025

**Comment by iFighting** [comment]
> 我在训练Sparse-rcnn的过程中，在project/Sparse-rcnn/sparsercnn/box_ops.py中对应的地方抛出了boxes的坐标值不合法的错误。请问可能是什么原因导致的呢？ 我打印了boxes的坐标值，发现其中是4个nan，网络结构和数据集都没有修改过。训练使用的是两张2080ti，batch size是8，学习率是0.0025

 you should decrease your learning rate

**Comment by ItsHelloWod** [comment]
> > 我在训练Sparse-rcnn的过程中，在project/Sparse-rcnn/sparsercnn/box_ops.py中对应的地方抛出了boxes的坐标值不合法的错误。请问可能是什么原因导致的呢？ 我打印了boxes的坐标值，发现其中是4个nan，网络结构和数据集都没有修改过。训练使用的是两张2080ti，batch size是8，学习率是0.0025
> 
> you should decrease your learning rate

I set it as 0.0012 and it also happened. Btw, why is it supposed to decrease learning rate? Big gradient updates results in big offsets?

**Comment by PeizeSun** [comment]
I guess 0.0012 is not small enough. Our default learning rate is 2.5e-5 with batchsize 16.
