### ISSUE TITLE
maxDet in eval_only is not proposals num?

### ISSUE THREAD

**Issue by Mingfeng-Wang** [PeizeSun/SparseR-CNN#35]
When I evaluate on a 300 proposals model, the eval info is:
![image](https://user-images.githubusercontent.com/42936096/102056313-25937700-3e27-11eb-8025-20ceedb1dd01.png)

The **maxDet** is 100 not the max proposals num, Should I **change** these **three threshold** or find another eval method?

My eval cmd is 
![image](https://user-images.githubusercontent.com/42936096/102056421-4fe53480-3e27-11eb-86c8-e2d006ebe40d.png)

**Comment by zzzzzz0407** [comment]
@Mingfeng-Wang The cocoeval will only test the top-100 result, therefore output 300 or 100 should return the same performance. You need not to change any thing.

**Comment by Mingfeng-Wang** [comment]
> @Mingfeng-Wang The cocoeval will only test the top-100 result, therefore output 300 or 100 should return the same performance. You need not to change any thing.

Actually I am testing CrowHuman which is a dense dataset even more than 400 person in a img. I tried to change **DETECTIONS PER IMAGE: 500**. But I did not work still maxDets = 100.

**Comment by Mingfeng-Wang** [comment]
@zzzzzz0407 
Where can I change the topk num? I have spent a long time to find it in code. Thanks.

**Comment by zzzzzz0407** [comment]
@Mingfeng-Wang You may should change the code in cocoeval and re-compile it to support large number eval.

**Comment by Mingfeng-Wang** [comment]
change cocoeval code
