### ISSUE TITLE
how to resume training

### ISSUE THREAD

**Issue by freedom521jin** [PeizeSun/SparseR-CNN#43]
Hi,when i try to resume training:
`--resume output/`
AssertionError: Override list has odd length: ['output/']; it must be a list of pairs.
So, how to resume training?

**Comment by iFighting** [comment]
> Hi,when i try to resume training:
> `--resume output/`
> AssertionError: Override list has odd length: ['output/']; it must be a list of pairs.
> So, how to resume training?

could you please show your full command?

**Comment by freedom521jin** [comment]
> > Hi,when i try to resume training:
> > `--resume output/`
> > AssertionError: Override list has odd length: ['output/']; it must be a list of pairs.
> > So, how to resume training?
> 
> could you please show your full command?

It has be solved,the command must be `--resume`, which does not need to add a pach.Thanks!

**Comment by freedom521jin** [comment]
> > Hi,when i try to resume training:
> > `--resume output/`
> > AssertionError: Override list has odd length: ['output/']; it must be a list of pairs.
> > So, how to resume training?
> 
> could you please show your full command?

It has be solved,the command must be --resume, which does not need to add a path.Thanks!
