### ISSUE TITLE
loss的三个组成部分  源自于detr？比例因子也直接采用detr的252？

### ISSUE THREAD

**Issue by henbucuoshanghai** [PeizeSun/SparseR-CNN#44]
Please select an issue template from
https://github.com/facebookresearch/detectron2/issues/new/choose .

Otherwise your issue will be closed.

**Comment by henbucuoshanghai** [comment]
分类，l1，giou源自detr？

**Comment by iFighting** [comment]
> 分类，l1，giou源自detr？

yes, we adopt the same setting with detr
