### ISSUE TITLE
请问怎样训练PASCAL   VOC2007 ，VOC2012呢？       tks

### ISSUE THREAD

**Issue by henbucuoshanghai** [PeizeSun/SparseR-CNN#46]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

For meaning of a config, please see
https://detectron2.readthedocs.io/modules/config.html#config-references

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work" for something you did, please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by iFighting** [comment]
> ## ❓ How to do something using detectron2
> Describe what you want to do, including:
> 
> 1. what inputs you will provide, if any:
> 2. what outputs you are expecting:
> 
> ## ❓ What does an API do and how to use it?
> Please link to which API or documentation you're asking about from
> https://detectron2.readthedocs.io/
> 
> For meaning of a config, please see
> https://detectron2.readthedocs.io/modules/config.html#config-references
> 
> NOTE:
> 
> 1. Only general answers are provided.
>    If you want to ask about "why X did not work" for something you did, please use the
>    [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.
> 2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.
> 3. We do not answer machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

VOC2007 ，VOC2012 is supported in detectron2, you can just replace the dataset in yaml

**Comment by henbucuoshanghai** [comment]
tks for help.
python projects/SparseRCNN/train_net.py --num-gpus 1  --config-file  configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml


The config file is configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml??   
I can use it directly?
All I need to do is download the VOC,and put the VOC in SparseR-CNN/datasets/VOC     ??? just like the coco?

**Comment by iFighting** [comment]
> tks for help.
> python projects/SparseRCNN/train_net.py --num-gpus 1 --config-file configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml
> 
> The config file is configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml??
> I can use it directly?
> All I need to do is download the VOC,and put the VOC in SparseR-CNN/datasets/VOC ??? just like the coco?

you need to use the config in sparsercnn, and modify the dataset as follows:
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
you also need to modify the num_class and iterations
