### ISSUE TITLE
How can I check the learned bboxes?

### ISSUE THREAD

**Issue by Mingfeng-Wang** [PeizeSun/SparseR-CNN#47]
I tried to draw learned boxes in detector forward in inference phase when it is before first cascade starts but it looked like wired that all boxes are located in the boundary of whole IMG.
I used the official coco res50_300_3x weights.
![image](https://user-images.githubusercontent.com/42936096/103271503-637ec680-49f5-11eb-990c-9a684b36cbf5.png)
![image](https://user-images.githubusercontent.com/42936096/103270899-fe76a100-49f3-11eb-8f82-0cae4710c259.png) 
![image](https://user-images.githubusercontent.com/42936096/103269957-e736b400-49f1-11eb-85f9-ccb3f40b71c2.png)

**Comment by PeizeSun** [comment]
Hi~
We double-checked this phenomenon over and over again, and we conclude that this is not a bug, this is exactly the learned proposal boxes before first stage if the initialization of proposal boxes before training is image size.

Also, we find that different initialization of proposal boxes before training could lead to different learned proposal boxes, for example,  Figure 5 in the Sparse R-CNN paper shows learned proposal boxes with random initialization.

**Comment by Mingfeng-Wang** [comment]
> Hi~
> We double-checked this phenomenon over and over again, and we conclude that this is not a bug, this is exactly the learned proposal boxes before first stage if the initialization of proposal boxes before training is image size.
> 
> Also, we find that different initialization of proposal boxes before training could lead to different learned proposal boxes, for example, Figure 5 in the Sparse R-CNN paper shows learned proposal boxes with random initialization.

Alright, I generated the learned proposals of myself trained model which look like much more normal. However I didn't check coco again yet.

**Comment by Dwrety** [comment]
Hi. Can you explain how exactly the initial proposal boxes are learned? I couldn't find any backpropagation operations that are associated with them. Basically the initial proposal boxes are only passed into the RoI Extractor and no gradient is generated for them in the backward step of RoIAlign.
