### ISSUE TITLE
Cannot reproduce the results for Res50

### ISSUE THREAD

**Issue by liyunsheng13** [PeizeSun/SparseR-CNN#51]
Hi
When I implement the code with yaml file sparsercnn.res50.100pro.3x.yaml and sparsercnn.res50.300pro.3x.yaml, I can only get mAP 40.8 and 42.5 respectively, both of which are about 2% worse than the reported results. I use 8 GPUS with batch size 16. I think the learning hyper parameters and initialization are the same as yours. Could you give me some hint about why the potential problem might be?

Thanks

**Comment by iFighting** [comment]
> Hi
> When I implement the code with yaml file sparsercnn.res50.100pro.3x.yaml and sparsercnn.res50.300pro.3x.yaml, I can only get mAP 40.8 and 42.5 respectively, both of which are about 2% worse than the reported results. I use 8 GPUS with batch size 16. I think the learning hyper parameters and initialization are the same as yours. Could you give me some hint about why the potential problem might be?
> 
> Thanks

could you please provide your full config? 
are you using our official code?

**Comment by liyunsheng13** [comment]
Yes, I use the official code with default settings. The log for sparsercnn.res50.300pro.3x.yaml can be download with this link [https://drive.google.com/file/d/1WdWWuXE9h9fNZKBDG212Kwwlv_qoSeyp/view?usp=sharing](url)

**Comment by PeizeSun** [comment]
> Yes, I use the official code with default settings. The log for sparsercnn.res50.300pro.3x.yaml can be download with this link [https://drive.google.com/file/d/1WdWWuXE9h9fNZKBDG212Kwwlv_qoSeyp/view?usp=sharing](url)
> Thanks for your time

I find in your log that you don't use model "detectron2://ImageNetPretrained/torchvision/R-50.pkl".

**Comment by liyunsheng13** [comment]
Yes, I have had R-50.pkl saved in my server. Maybe the one I have is not the same  as yours. I will double check.
