### ISSUE TITLE
An error was encountered while the demo was running

### ISSUE THREAD

**Issue by Baboom-l** [PeizeSun/SparseR-CNN#52]
run the Visualize SparseR-CNN of codes: 

python demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml  --input 2.jpg --output test.jpg --confidence-threshold 0.4 --opts MODEL.WEIGHTS  r50_100pro_3x_model.pth.qbl

Meet bug:
D:\NANa\SparseR-CNN-main>python demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml  --input 2.jpg --output test.jpg --confidence-threshold 0.4 --opts MODEL.WEIGHTS r50_100pro_3x_model.pth.qbl
[01/04 18:07:38 detectron2]: Arguments: Namespace(confidence_threshold=0.4, config_file='projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml', input=['2.jpg'], opts=['MODEL.WEIGHTS', 'r50_100pro_3x_model.pth.qbl'], output='test.jpg', video_input=None, webcam=False)
[01/04 18:07:40 fvcore.common.checkpoint]: Loading checkpoint from r50_100pro_3x_model.pth.qbl
Traceback (most recent call last):
  File "demo.py", line 80, in <module>
    demo = VisualizationDemo(cfg)
  File "D:\NANa\SparseR-CNN-main\predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "D:\anaconda\envs\p171\lib\site-packages\detectron2\engine\defaults.py", line 194, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "D:\anaconda\envs\p171\lib\site-packages\fvcore\common\checkpoint.py", line 122, in load
    checkpoint = self._load_file(path)
  File "D:\anaconda\envs\p171\lib\site-packages\detectron2\checkpoint\detection_checkpoint.py", line 54, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "D:\anaconda\envs\p171\lib\site-packages\fvcore\common\checkpoint.py", line 219, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "D:\anaconda\envs\p171\lib\site-packages\torch\serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\anaconda\envs\p171\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

my environment
win10+cuda11+python 3.7+torch 1.7.1

**Comment by iFighting** [comment]
> run the Visualize SparseR-CNN of codes:
> 
> python demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml --input 2.jpg --output test.jpg --confidence-threshold 0.4 --opts MODEL.WEIGHTS r50_100pro_3x_model.pth.qbl
> 
> Meet bug:
> D:\NANa\SparseR-CNN-main>python demo.py --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml --input 2.jpg --output test.jpg --confidence-threshold 0.4 --opts MODEL.WEIGHTS r50_100pro_3x_model.pth.qbl
> [01/04 18:07:38 detectron2]: Arguments: Namespace(confidence_threshold=0.4, config_file='projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml', input=['2.jpg'], opts=['MODEL.WEIGHTS', 'r50_100pro_3x_model.pth.qbl'], output='test.jpg', video_input=None, webcam=False)
> [01/04 18:07:40 fvcore.common.checkpoint]: Loading checkpoint from r50_100pro_3x_model.pth.qbl
> Traceback (most recent call last):
> File "demo.py", line 80, in
> demo = VisualizationDemo(cfg)
> File "D:\NANa\SparseR-CNN-main\predictor.py", line 35, in **init**
> self.predictor = DefaultPredictor(cfg)
> File "D:\anaconda\envs\p171\lib\site-packages\detectron2\engine\defaults.py", line 194, in **init**
> checkpointer.load(cfg.MODEL.WEIGHTS)
> File "D:\anaconda\envs\p171\lib\site-packages\fvcore\common\checkpoint.py", line 122, in load
> checkpoint = self._load_file(path)
> File "D:\anaconda\envs\p171\lib\site-packages\detectron2\checkpoint\detection_checkpoint.py", line 54, in _load_file
> loaded = super()._load_file(filename) # load native pth checkpoint
> File "D:\anaconda\envs\p171\lib\site-packages\fvcore\common\checkpoint.py", line 219, in _load_file
> return torch.load(f, map_location=torch.device("cpu"))
> File "D:\anaconda\envs\p171\lib\site-packages\torch\serialization.py", line 587, in load
> with _open_zipfile_reader(opened_file) as opened_zipfile:
> File "D:\anaconda\envs\p171\lib\site-packages\torch\serialization.py", line 242, in **init**
> super(_open_zipfile_reader, self).**init**(torch._C.PyTorchFileReader(name_or_buffer))
> RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> my environment
> win10+cuda11+python 3.7+torch 1.7.1

the code is not supported in windows platform
