### ISSUE TITLE
the ap is higher than 1,why?

### ISSUE THREAD

**Issue by henbucuoshanghai** [PeizeSun/SparseR-CNN#56]
| category   | AP    | category   | AP    | category   | AP    |
|:-----------|:------|:-----------|:------|:-----------|:------|
| xxxxx| 1.891 | yyyyy    | 0.838 | zzzzz     | 0.634 |

**Comment by henbucuoshanghai** [comment]
also   the ap may larger than 2.0                 what is wrong?

**Comment by iFighting** [comment]
> category	AP	category	AP	category	AP
> xxxxx	1.891	yyyyy	0.838	zzzzz	0.634

actually the mAP is 0.0189
