### ISSUE TITLE
Randomness in the results for COCO

### ISSUE THREAD

**Issue by AyeshaNirma** [PeizeSun/SparseR-CNN#62]
I have trained Sparse R-CNN multiple times and I have observed some degree of randomness (which is usual in almost all detection pipelines). I just wanted to know how much deviation one can expect in the results of Sparse R-CNN without ringing bells. Is it safe to say +-0.3 ? or is it more than that ? 

Reason why I believe it is important is that if someone wants to compare against an improved version of Sparse RCNN he/she should know the rough bounds.

**Comment by PeizeSun** [comment]
Hi~
Based on our experiments(we fix the random seed), it is safe to say +-0.3.

**Comment by AyeshaNirma** [comment]
Thanks for the response.
