### ISSUE TITLE
在小数据集上for example （train:60 test:13）如何调优参数，使用默认配置测试结果不太好

### ISSUE THREAD

**Issue by csliuchang** [PeizeSun/SparseR-CNN#64]
###get better results in small dataset for example : balloon dataset
could you give me some configs advice?
for example:
lr: 
proposed boxes:
muti-scale:

**Comment by iFighting** [comment]
i suggest you to use a powerful detection pretrained mode(such as coco)l to fine-tune on your dataset.
or you can also only train the classifier
