### ISSUE TITLE
How the refinement and de-duplication is performed?

### ISSUE THREAD

**Issue by jiangsy** [PeizeSun/SparseR-CNN#7]
I noticed that the paper mentions an iterative training by feeding the previously predicted bbox and feature. Could you help identify which part of the code corresponds to this. And may I ask how deduplication is achieved in this process, since the paper claims to be free of NMS?

**Comment by PeizeSun** [comment]
The iterative process is at: https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseR-CNN/sparsercnn/head.py#L103 L103-109

The deduplication is from optimal bipartite matching in training(https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseR-CNN/sparsercnn/loss.py#L273) and self-attention module(https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseR-CNN/sparsercnn/head.py#L188).

**Comment by jiangsy** [comment]
Thanks for a quick response.

Some additional tiny questions about de-duplication. I noticed the bipartite matching. I just wonder should the number of proposed bbox remain fixed after the 1st round of matching (because you have selected the best matched bboxes)?

**Comment by PeizeSun** [comment]
This is a very interesting question~
In my opinion, the number of proposed boxes could be different in different rounds, for example, gradually decreasing from 1st round to final round. We haven't tried it. If you're interested, you could try it and share the result with us.

**Comment by jiangsy** [comment]
Thank you again for your response
