### ISSUE TITLE
Will you release DetCo code and model version?

### ISSUE THREAD

**Issue by Mingfeng-Wang** [PeizeSun/SparseR-CNN#73]
Thanks for your replying.

**Comment by PeizeSun** [comment]
Hi~
Config file is [detco.yaml](https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseRCNN/configs/sparsercnn.res50.300pro.3x.detco.yaml).
Pre-train model is in [DetCo repo](https://github.com/xieenze/DetCo).

We have no plan to release model.

**Comment by Mingfeng-Wang** [comment]
> Hi~
> Config file is [detco.yaml](https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseRCNN/configs/sparsercnn.res50.300pro.3x.detco.yaml).
> Pre-train model is in [DetCo repo](https://github.com/xieenze/DetCo).
> 
> We have no plan to release model.

I find it really requires GPU memory , I tried to request 4 48 v100 GPU but in waiting list in our cluster. For saving time, is it enough with 1000 proposals、 (1000,1666) img size、 batchsize 16? Or could you give me an example how much memory you used in training with config?

**Comment by PeizeSun** [comment]
For training config, please refer to [detco.yaml](https://github.com/PeizeSun/SparseR-CNN/blob/main/projects/SparseRCNN/configs/sparsercnn.res50.300pro.3x.detco.yaml).
We use 8 V100 gpus, and each gpu memory cost is about 15G.
