### ISSUE TITLE
Does input data annotations need to be normalized coordinate before training?

### ISSUE THREAD

**Issue by tson1997** [PeizeSun/SparseR-CNN#74]
Good day!
Thank you for the amazing work. I am amazed by the sparse to sparse idea that you guys implement in the paper.
Coming to my question, I have a custom dataset that has a json format and works well on detectron2 faster rcnn. It bbox annotation contain x,y,w,h of the bounding box, but they are **NOT normalized**. I want to train my dataset with SparseR-CNN. Do I need to normalize the coordinate and sizes before training?

**Comment by Mingfeng-Wang** [comment]
I think it has already done in preprocess func within detector.py.

**Comment by tson1997** [comment]
Thank you. It seems like that. I trained with custom dataset and it is fine 👍
