### ISSUE TITLE
保存模型与提供模型大小之间的差异

### ISSUE THREAD

**Issue by luyao-cv** [PeizeSun/SparseR-CNN#79]
非常感谢你的工作，但是我想请问为什么你提供的r50 100权重大小只有几百兆，但是我在训练你的模型保存的却是1.19G这么大？

**Comment by iFighting** [comment]
> 非常感谢你的工作，但是我想请问为什么你提供的r50 100权重大小只有几百兆，但是我在训练你的模型保存的却是1.19G这么大？

we have publish the model(not include the optimizer status, etc....)
