### ISSUE TITLE
Why does the "cost_class" include two items, i.e. pos_cost_class and neg_cost_class?

### ISSUE THREAD

**Issue by chixma** [PeizeSun/SparseR-CNN#8]
https://github.com/PeizeSun/SparseR-CNN/blob/daf86305eb5e1a1c93d001b457e5d90a8b40e032/projects/SparseR-CNN/sparsercnn/loss.py#L251
Why does the "cost_class" include two items, i.e. pos_cost_class and neg_cost_class? While if self.use_focal == False, cost_class = -out_prob[:, tgt_ids], which includes only one item and corresponds to "pos_cost_class".

**Comment by PeizeSun** [comment]
Hi~
In focal loss, classification is K binary classifiers(K is number of categories), binary classifier contains positive item and negative item.
In softmax loss, classification is one multi-category classifier, probability of ground-truth  category is selected.

**Comment by chixma** [comment]
@PeizeSun Thanks for your reply!. However, I'm a little confused. 
If my understanding is correct, cost_class[i, j] indicates the classification cost if the i-th detected box matched with the j-th gt box. So, given this possible pair (i, j), the classification cost is measured by the predicted binary classification result of the pred_box i for the gt_class(gt_box j), e.g., gt_class of the gt_box j is "person". I think it is "pos_cost_class", and I can't understand why "- neg_cost_class" is needed.

**Comment by PeizeSun** [comment]
For the result of the pred_box i for the gt_class(gt_box j), if its probability is higher, its pos_cost is smaller, at the same time, its neg_cost is bigger, pos_cost **minus** neg_cost is smaller, that's exactly what is needed.  You could understand that the pos item and neg item work together. 

BTW, our experiments find that only pos item doesn't work.

**Comment by abcxs** [comment]
> For the result of the pred_box i for the gt_class(gt_box j), if its probability is higher, its pos_cost is smaller, at the same time, its neg_cost is bigger, pos_cost **minus** neg_cost is smaller, that's exactly what is needed. You could understand that the pos item and neg item work together.
> 
> BTW, our experiments find that only pos item doesn't work.

I'm a little confused.
A similar effect can be achieved by using pos_cost alone, without considering the experiment
