### ISSUE TITLE
Init proposal box Visualization

### ISSUE THREAD

**Issue by junha1125** [PeizeSun/SparseR-CNN#85]
Hi. I have a querstion.

I debuged the code [projexts/sparseRCNN/sarsercnn/head.py]
I visualize `init_bboxes` in `forward` of `DynamicHead`

![image](https://user-images.githubusercontent.com/46951365/117933889-04cf3f00-b33d-11eb-9a9f-7fc94f770019.png)

But in your paper, the boxes visualized was this.

![image](https://user-images.githubusercontent.com/46951365/117933995-20d2e080-b33d-11eb-80f5-48511730ab87.png)

Is there something I am missing?
Why are the two box visualization image different?

**Comment by PeizeSun** [comment]
Hi~
Please refer to [issues 47](https://github.com/PeizeSun/SparseR-CNN/issues/47)

**Comment by junha1125** [comment]
Thank you very mush for your quick reply.

**Comment by Deicide-PiLi** [comment]
I have the same confusion. Has the author explained the issue, and where?
