### ISSUE TITLE
Change ADAMW to SGD

### ISSUE THREAD

**Issue by to-lie-down** [PeizeSun/SparseR-CNN#94]
Thanks for your awesome work.

Have you tried using SGD instead of ADAMW? If i want to use the SGD to train the model, what shoule I do?

**Comment by PeizeSun** [comment]
Hi~
I am sorry for replying so late. You can use the SGD by
```
python projects/SparseRCNN/train_net.py --num-gpus 8 --config-file projects/SparseRCNN/configs/sparsercnn.res50.100pro.3x.yaml SOLVER.OPTIMIZER SGD
```

However, our experiment shows the model trained with SGD doesn't converge.

**Comment by to-lie-down** [comment]
Thanks you for your reply.

I'm a little confused about the last experiment in the paper.

If you use Swin Transformer, how to set the Image size?

fix or random scale?

**Comment by to-lie-down** [comment]
@PeizeSun

**Comment by to-lie-down** [comment]
And do you have the config using the Swin Transformer to train Sparse R-CNN?
