### ISSUE TITLE
Confusing about the performance in the paper

### ISSUE THREAD

**Issue by YJHMITWEB** [PeizeSun/SparseR-CNN#96]
Hi, thanks for your great work.

I am a little confused about the tables you provided in the paper. 

In Table.1, you mentioned that Sparse RCNN R50-FPN with 100 proposals can reach a 42.8 AP on COCO val, as far as I can tell, this model configuration has no difference compared to the 42.3 AP model which you mentioned in Table.3, Table.5, Table.6, Table.7, Table.8, Table.9, Table.10. 

Moreover, the rest metrics of the 42.8 AP model, e.g. AP50, AP75, APs, APm, APl are identical to that of the 42.3 model, both are 61.2, 45.7, 26.7, 44.6 and 57.6. 

Cleverly it is impossible, so I am wondering which is the real result.

**Comment by YJHMITWEB** [comment]
Also I see that you mentioned your model has a 0.3 AP noise, but again, it does not explain the difference between 42.3 and 42.8.

**Comment by PeizeSun** [comment]
Hi~
As we mention in Update in README, higher performance for Sparse R-CNN is reported by setting the dropout rate as 0.0.
42.8 is the dropout rate as 0.0, 42.3 is the dropout rate larger than 0.0.

We are sorry for this confusing.

**Comment by YJHMITWEB** [comment]
Thanks, I get it, should've read more carefully..
